apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: cc-kcp
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      clusterName: kurator-cluster
      imageRepository:
      featureGates:
        PodOverhead: true
        NodeSwap: true
    initConfiguration:
    joinConfiguration:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: customMachine
      name: cc-custommachine
      namespace: default
  version: v1.24.6
