apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kurator-serving-cert
  creationTimestamp: null
  name: fleet-manager-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: kurator-webhook-service-fleet
        namespace: {{ .Release.Namespace }}
        path: /validate-apps-kurator-dev-v1alpha1-application # do not change this
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validation.application.apps.kurator.dev
    rules:
      - apiGroups:
          - apps.kurator.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - applications
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kurator-serving-cert
  creationTimestamp: null
  name: fleet-manager-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: kurator-webhook-service-fleet
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-kurator-dev-v1alpha1-application # do not change this
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mutation.application.apps.kurator.dev
    rules:
      - apiGroups:
          - apps.kurator.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - applications
    sideEffects: None
