apiVersion: apps.kurator.dev/v1alpha1
kind: Application
metadata:
  name: app-gitrepo
  namespace: app-gitrepo
spec:
  source:
    gitRepo:
      interval: 3m0s
      ref:
        branch: master
      timeout: 1m0s
      url: https://github.com/stefanprodan/podinfo
  syncPolicy:
    - destination:
        fleet: fleet-gitrepo
      kustomization:
        interval: 5m0s
        path: ./deploy/webapp
        prune: true
        timeout: 2m0s
