apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kurator-serving-cert
  creationTimestamp: null
  name: cluster-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: kurator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cluster-kurator-dev-v1alpha1-cluster # do not change this
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.cluster.cluster.kurator.dev
  rules:
  - apiGroups:
    - cluster.kurator.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: kurator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-customcluster # get this path from webhook service log
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.customcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customclusters
  sideEffects: None
- admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    service:
      name: kurator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-cluster-kurator-dev-v1alpha1-attachedcluster # get this path from webhook service log
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.attachedcluster.cluster.kurator.dev
  rules:
    - apiGroups:
        - cluster.kurator.dev
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - attachedclusters
  sideEffects: None
