apiVersion: apps.kurator.dev/v1alpha1
kind: Application
metadata:
  name: abtesting-nginx-demo
  namespace: default
spec:
  source:
    gitRepository:
      interval: 3m0s
      ref:
        branch: master
      timeout: 1m0s
      url: https://github.com/stefanprodan/podinfo
  syncPolicies:
    - destination:
        fleet: quickstart
      kustomization:
        interval: 0s
        path: ./deploy/webapp
        prune: true
        timeout: 2m0s
      rollout:
        testLoader: true
        trafficRoutingProvider: nginx
        workload:
          apiVersion: apps/v1
          name: backend
          kind: Deployment
          namespace: webapp
        serviceName: backend
        port: 9898
        rolloutPolicy:
          trafficRouting:
            analysisTimes: 3
            timeoutSeconds: 60
            host: "app.example.com"
            match:
              - headers:
                  x-canary:
                    exact: "insider"
              - headers:
                  cookie:
                    exact: "canary"
          trafficAnalysis:
            checkIntervalSeconds: 90
            checkFailedTimes: 2
            metrics:
              - name: my-metric
                intervalSeconds: 90
                thresholdRange:
                  min: 99
                customMetric:
                  provider:
                    type: prometheus
                    address: http://ingress-nginx-flagger-kurator-member-prometheus.ingress-nginx:9090
                  query: |
                    sum(
                      rate(
                        http_requests_total{
                          status!~"5.*"
                        }[{{ interval }}]
                      )
                    )
                    /
                    sum(
                      rate(
                        http_requests_total[{{ interval }}]
                      )
                    ) * 100
            webhooks:
              timeoutSeconds: 60
              command:
                - "hey -z 1m -q 10 -c 2 http://app.example.com/"
          rolloutTimeoutSeconds: 600
    - destination:
        fleet: quickstart
      kustomization:
        targetNamespace: default
        interval: 5m0s
        path: ./kustomize
        prune: true
        timeout: 2m0s
