apiVersion: v1
kind: Namespace
metadata:
  name: avalanche
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  namespace: avalanche
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
      labels:
        app: avalanche
    spec:
      containers:
        - name: pg-avalanche
          image: quay.io/freshtracks.io/avalanche:latest
          args:
            - "--metric-count=10"
            - "--label-count=1"
            - "--series-count=1"
            - "--port=9001"
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: avalanche-svc
  namespace: avalanche
  labels:
    app: avalanche
spec:
  ports:
    - port: 9001
      targetPort: 9001
      name: http-avalanche
  type: ClusterIP
  clusterIP: None
  selector:
    app: avalanche
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: avalanche-monitor
  namespace: avalanche
  labels:
    monitoring: avalanche
spec:
  jobLabel: avalanche
  targetLabels: [app]
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [avalanche] }
  namespaceSelector:
    any: true
  endpoints:
    - port: http-avalanche
      interval: 15s
